# Site settings
title: Sneha Tilak
email: sneha.tilak26@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Computer Science Graduate Student at Indiana University - Bloomington.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://tilaks26.github.io" # the base hostname & protocol for your site
github_username:  tilaks26

# Build settings
markdown: kramdown
